env:
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: true
  SharedArrayBuffer: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  semi: off
  no-console: off
  quotes: [2, 'single', 'avoid-escape']
